package com.szmt.sec.po;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StuId
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuName
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuAcademy
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String stuacademy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPhone
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String stuphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPlace
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String stuplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gpa
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    private String gpa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StuId
     *
     * @return the value of student.StuId
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StuId
     *
     * @param stuid the value for student.StuId
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuName
     *
     * @return the value of student.stuName
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuName
     *
     * @param stuname the value for student.stuName
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuAcademy
     *
     * @return the value of student.stuAcademy
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getStuacademy() {
        return stuacademy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuAcademy
     *
     * @param stuacademy the value for student.stuAcademy
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setStuacademy(String stuacademy) {
        this.stuacademy = stuacademy == null ? null : stuacademy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPhone
     *
     * @return the value of student.stuPhone
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getStuphone() {
        return stuphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPhone
     *
     * @param stuphone the value for student.stuPhone
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setStuphone(String stuphone) {
        this.stuphone = stuphone == null ? null : stuphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPlace
     *
     * @return the value of student.stuPlace
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getStuplace() {
        return stuplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPlace
     *
     * @param stuplace the value for student.stuPlace
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setStuplace(String stuplace) {
        this.stuplace = stuplace == null ? null : stuplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gpa
     *
     * @return the value of student.gpa
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public String getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gpa
     *
     * @param gpa the value for student.gpa
     *
     * @mbggenerated Tue Nov 10 17:03:16 CST 2015
     */
    public void setGpa(String gpa) {
        this.gpa = gpa == null ? null : gpa.trim();
    }
}