package com.szmt.sec.po;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uname
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.cellphone
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uname
     *
     * @return the value of users.uname
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uname
     *
     * @param uname the value for users.uname
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.cellphone
     *
     * @return the value of users.cellphone
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.cellphone
     *
     * @param cellphone the value for users.cellphone
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Wed Nov 11 20:53:28 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}